// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcsHVDtshoWBjW7PzxqKp8BK9lCtL33RE',
    appId: '1:606517559324:web:210f4e08e9f9a2fe641fd9',
    messagingSenderId: '606517559324',
    projectId: 'background-eraser-2e9c9',
    authDomain: 'background-eraser-2e9c9.firebaseapp.com',
    storageBucket: 'background-eraser-2e9c9.firebasestorage.app',
    measurementId: 'G-29V4FQGEK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_0ZcLcYjRMOd-UBxHwi-VLylaLMh1p28',
    appId: '1:606517559324:android:dafa60f6ab10246c641fd9',
    messagingSenderId: '606517559324',
    projectId: 'background-eraser-2e9c9',
    storageBucket: 'background-eraser-2e9c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn2k20taUEkuKulQp2AlPWn2ij7i-D4Ho',
    appId: '1:606517559324:ios:084674ba60186de2641fd9',
    messagingSenderId: '606517559324',
    projectId: 'background-eraser-2e9c9',
    storageBucket: 'background-eraser-2e9c9.firebasestorage.app',
    iosBundleId: 'com.example.backgroundEraser',
  );
}
